"""update models add l

Revision ID: 04203d1db310
Revises: 57b45412db85
Create Date: 2022-04-02 16:10:30.071193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04203d1db310'
down_revision = '57b45412db85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
