"""update models add asl

Revision ID: 0fb4a4307cde
Revises: abc73be0acfb
Create Date: 2022-04-03 11:33:19.796898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb4a4307cde'
down_revision = 'abc73be0acfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'forum', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forum', type_='unique')
    # ### end Alembic commands ###
