"""add forum models

Revision ID: 1e108fc73a16
Revises: 775faf55ee33
Create Date: 2022-02-03 21:05:51.414670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e108fc73a16'
down_revision = '775faf55ee33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
