"""change models 2

Revision ID: 1f3730895b5d
Revises: 613913b2f8f0
Create Date: 2022-06-22 12:12:05.836618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3730895b5d'
down_revision = '613913b2f8f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
