"""update code 2

Revision ID: 3776d5cd5d74
Revises: 833d4831f6f3
Create Date: 2022-04-15 15:47:27.416163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3776d5cd5d74'
down_revision = '833d4831f6f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
