"""update code 3

Revision ID: 453b0f9d16f7
Revises: 3776d5cd5d74
Create Date: 2022-04-15 16:00:43.625107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453b0f9d16f7'
down_revision = '3776d5cd5d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
