"""update models add asql

Revision ID: 4f8d02ceee97
Revises: 0fb4a4307cde
Create Date: 2022-04-03 11:41:20.656367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8d02ceee97'
down_revision = '0fb4a4307cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
