"""update models add l

Revision ID: 57b45412db85
Revises: c2f0e3e6b0fa
Create Date: 2022-04-02 16:05:19.565627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b45412db85'
down_revision = 'c2f0e3e6b0fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
