"""second update base model

Revision ID: 5a68a0f4e69e
Revises: 60d8fb7d77d9
Create Date: 2022-03-19 20:25:27.444607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a68a0f4e69e'
down_revision = '60d8fb7d77d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_code', sa.Column('user', sa.String(), nullable=True))
    op.create_foreign_key(None, 'verification_code', 'users', ['user'], ['email'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_code', type_='foreignkey')
    op.drop_column('verification_code', 'user')
    # ### end Alembic commands ###
