"""update images model

Revision ID: 5b741b2fa00b
Revises: 914bbcaf5a6a
Create Date: 2022-02-04 00:58:07.989371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b741b2fa00b'
down_revision = '914bbcaf5a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images_forum_discussion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forum_id', sa.Integer(), nullable=True),
    sa.Column('images', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['forum_id'], ['forum_discussion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_forum_discussion_id'), 'images_forum_discussion', ['id'], unique=True)
    op.drop_constraint('forum_images_id_fkey', 'forum', type_='foreignkey')
    op.drop_column('forum', 'images_id')
    op.drop_constraint('forum_discussion_images_id_fkey', 'forum_discussion', type_='foreignkey')
    op.drop_column('forum_discussion', 'images_id')
    op.add_column('images', sa.Column('forum_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'images', 'forum', ['forum_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'forum_id')
    op.add_column('forum_discussion', sa.Column('images_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('forum_discussion_images_id_fkey', 'forum_discussion', 'images', ['images_id'], ['id'])
    op.add_column('forum', sa.Column('images_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('forum_images_id_fkey', 'forum', 'images', ['images_id'], ['id'])
    op.drop_index(op.f('ix_images_forum_discussion_id'), table_name='images_forum_discussion')
    op.drop_table('images_forum_discussion')
    # ### end Alembic commands ###
