"""second update base model

Revision ID: 5bb570222f20
Revises: 4f8d02ceee97
Create Date: 2022-04-12 16:51:32.450932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb570222f20'
down_revision = '4f8d02ceee97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
