"""update code model to email

Revision ID: 60d8fb7d77d9
Revises: 1fec5ab79436
Create Date: 2022-03-19 20:19:26.611181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d8fb7d77d9'
down_revision = '1fec5ab79436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'verification_code', ['code'])
    op.drop_constraint('verification_code_user_fkey', 'verification_code', type_='foreignkey')
    op.drop_column('verification_code', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_code', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('verification_code_user_fkey', 'verification_code', 'users', ['user'], ['email'], ondelete='CASCADE')
    op.drop_constraint(None, 'verification_code', type_='unique')
    # ### end Alembic commands ###
