"""change models

Revision ID: 613913b2f8f0
Revises: ef2ba99594c4
Create Date: 2022-06-22 11:41:08.700450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613913b2f8f0'
down_revision = 'ef2ba99594c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
