"""add article model

Revision ID: 6fa347c68c8c
Revises: cb44bbf53147
Create Date: 2022-04-19 17:51:40.222477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa347c68c8c'
down_revision = 'cb44bbf53147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
