"""change models 3

Revision ID: 90ab7df9215c
Revises: dcd186932767
Create Date: 2022-06-22 12:13:54.969620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ab7df9215c'
down_revision = 'dcd186932767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('date', sa.String(length=50), nullable=True))
    op.drop_constraint('appointment_date_time_key', 'appointment', type_='unique')
    op.create_unique_constraint(None, 'appointment', ['date'])
    op.drop_column('appointment', 'date_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('date_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointment', type_='unique')
    op.create_unique_constraint('appointment_date_time_key', 'appointment', ['date_time'])
    op.drop_column('appointment', 'date')
    # ### end Alembic commands ###
