"""update code model to email

Revision ID: 914bbcaf5a6a
Revises: fd6ec68e5e66
Create Date: 2022-02-03 22:40:38.898619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914bbcaf5a6a'
down_revision = 'fd6ec68e5e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
