"""second update base model

Revision ID: 93965f8c6ba7
Revises: 5bb570222f20
Create Date: 2022-04-14 12:50:06.644114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93965f8c6ba7'
down_revision = '5bb570222f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('forum_discussion_title_key', 'forum_discussion', type_='unique')
    op.drop_column('forum_discussion', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_discussion', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('forum_discussion_title_key', 'forum_discussion', ['title'])
    # ### end Alembic commands ###
