"""chande desc to type

Revision ID: 9a5c8a222bfd
Revises: b2284f66a084
Create Date: 2022-06-15 12:21:35.876359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5c8a222bfd'
down_revision = 'b2284f66a084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('type', sa.Enum('SINGLE', 'MULTIPLE', name='typeenum'), nullable=True))
    op.drop_column('appointment', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('appointment', 'type')
    # ### end Alembic commands ###
