"""update models add asl

Revision ID: a510dda4453f
Revises: b5fdd815ccc5
Create Date: 2022-04-02 16:11:35.547797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a510dda4453f'
down_revision = 'b5fdd815ccc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
