"""update models add asl

Revision ID: abc73be0acfb
Revises: a510dda4453f
Create Date: 2022-04-03 11:26:36.469469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc73be0acfb'
down_revision = 'a510dda4453f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
