"""add gallery model

Revision ID: b2284f66a084
Revises: 1ef8d8152cf7
Create Date: 2022-06-14 17:11:06.035440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2284f66a084'
down_revision = '1ef8d8152cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_id'), 'gallery', ['id'], unique=True)
    op.create_table('gallery_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=True),
    sa.Column('images', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_image_id'), 'gallery_image', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_image_id'), table_name='gallery_image')
    op.drop_table('gallery_image')
    op.drop_index(op.f('ix_gallery_id'), table_name='gallery')
    op.drop_table('gallery')
    # ### end Alembic commands ###
