"""update models add l

Revision ID: b5fdd815ccc5
Revises: 04203d1db310
Create Date: 2022-04-02 16:11:11.716429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5fdd815ccc5'
down_revision = '04203d1db310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
