"""update models add l

Revision ID: c2f0e3e6b0fa
Revises: cec140634dc1
Create Date: 2022-04-01 14:02:04.464651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f0e3e6b0fa'
down_revision = 'cec140634dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
