"""update code 5

Revision ID: cb44bbf53147
Revises: 453b0f9d16f7
Create Date: 2022-04-19 17:50:47.771737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb44bbf53147'
down_revision = '453b0f9d16f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
