"""гзвфеу appointments model

Revision ID: d690dceb40ed
Revises: fc6133c70164
Create Date: 2022-05-05 11:32:15.735735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd690dceb40ed'
down_revision = 'fc6133c70164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'appointment', ['date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='unique')
    # ### end Alembic commands ###
