"""change models 3

Revision ID: dcd186932767
Revises: 1f3730895b5d
Create Date: 2022-06-22 12:13:33.948273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dcd186932767'
down_revision = '1f3730895b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('date_time', sa.String(length=50), nullable=True))
    op.drop_constraint('appointment_date_key', 'appointment', type_='unique')
    op.create_unique_constraint(None, 'appointment', ['date_time'])
    op.drop_column('appointment', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointment', type_='unique')
    op.create_unique_constraint('appointment_date_key', 'appointment', ['date'])
    op.drop_column('appointment', 'date_time')
    # ### end Alembic commands ###
