"""change models

Revision ID: e64e6ee3737c
Revises: 61dcfd1aca8b
Create Date: 2022-06-16 15:45:23.780558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64e6ee3737c'
down_revision = '61dcfd1aca8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
