"""change models

Revision ID: ef2ba99594c4
Revises: e64e6ee3737c
Create Date: 2022-06-16 16:54:54.396559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2ba99594c4'
down_revision = 'e64e6ee3737c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery_image', sa.Column('gallery_title_id', sa.Integer(), nullable=True))
    op.drop_constraint('gallery_image_gallery_id_fkey', 'gallery_image', type_='foreignkey')
    op.create_foreign_key(None, 'gallery_image', 'gallery', ['gallery_title_id'], ['id'], ondelete='CASCADE')
    op.drop_column('gallery_image', 'gallery_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery_image', sa.Column('gallery_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'gallery_image', type_='foreignkey')
    op.create_foreign_key('gallery_image_gallery_id_fkey', 'gallery_image', 'gallery', ['gallery_id'], ['id'], ondelete='CASCADE')
    op.drop_column('gallery_image', 'gallery_title_id')
    # ### end Alembic commands ###
